# Generated by Django 5.2.6 on 2026-02-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
